# Generated by Django 2.2.7 on 2019-11-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('default_name', models.CharField(max_length=50)),
                ('icon', models.FileField(upload_to='')),
            ],
        ),
    ]
