# Generated by Django 2.2.7 on 2019-11-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='icon',
            field=models.ImageField(default='images/NotFound.png', upload_to='images/'),
        ),
    ]
