# Generated by Django 2.2.7 on 2019-11-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20191105_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='default_name',
            new_name='defaultName',
        ),
    ]
